-- ============================================================
-- Amanda Cards – Supabase SQL Schema
-- Referral schema removed; no referral-related table or columns are created here.
-- ============================================================
